name: crud_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.1
  dio: ^5.4.3+1
  provider: ^6.1.2
  path_provider: ^2.1.3

flutter:
  uses-material-design: true
